[package]
name = "dsf-core"
version = "0.1.2"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
description = "DSF core object definitions"
repository = "https://github.com/dist-svc/dsf-core"
homepage = "https://github.com/dist-svc"
keywords = ["DSF", "distributed"]
license = "MPL-2.0"
edition = "2018"

[features]
std = [ "managed/std", "bytes/std", "base64/std", "byteorder/std", "sodiumoxide/std", "sha2/std", "chrono/std", "strum" ]
alloc = [ "base64/alloc", "chrono/alloc" ]
default = [ "std", "serde" ]


[dependencies]
bitflags = "1.2.1"
#derive_builder = "0.7.0"
log = "0.4.6"
#ls = "0.0.0"
#newtype_array = "0.1.6"
slice-ext = "0.1.0"
async-trait = "0.1.19"
strum_macros = "0.17.1"
no-std-net = { version = "0.3.0", optional = true }
rand_core = { version = "*", default_features = false }

[dependencies.managed]
version = "0.7.1"
default_features = false

[dependencies.sodiumoxide]
version = "0.2.5"
#git = "https://github.com/sodiumoxide/sodiumoxide.git"
#branch = "cc_build_libsodium"
default_features = false

[dependencies.bytes]
version = "0.5.4"
default_features = false

[dependencies.base64]
version = "0.12.1"
default_features = false

[dependencies.byteorder]
version = "1.3.2"
default_features = false

[dependencies.sha2]
version = "0.8.1"
default_features = false

[dependencies.chrono]
version = "0.4.11"
default_features = false

[dependencies.strum]
version = "0.18.0"
optional = true

[dependencies.diesel]
version = "1.4.3"
optional = true

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[patch.crates-io]
#sodiumoxide = { path = "../../sodiumoxide" }

#sodiumoxide = { git = "https://github.com/ryankurte/sodiumoxide", branch = "fix/arm-none-eabi" }
#sodiumoxide = { git = "https://github.com/sodiumoxide/sodiumoxide.git", branch = "cc_build_libsodium" }

#libsodium-sys = { git = "https://github.com/ryankurte/libsodium", branch="feature/cargo-compat" }