[package]
name = "dsf-core"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
description = "DSF core object definitions"
repository = "https://github.com/dist-svc/dsf-core"
homepage = "https://github.com/dist-svc"
keywords = ["DSF", "distributed"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
base64 = "0.10.1"
bitflags = "1.1.0"
byteorder = "1.2.7"
bytes = "0.4.11"
chrono = "0.4.6"
derive_builder = "0.7.0"
futures = "0.3.1"
futures-timer = "0.1.1"
log = "0.4.6"
ls = "0.0.0"
newtype_array = "0.1.6"
rand = "0.6.4"
slice-ext = "0.1.0"
sodiumoxide = "0.2.0"
async-trait = "0.1.19"
ed25519-dalek = "0.9.1"
sha2 = "0.8.1"

[dependencies.diesel]
version = "1.4.3"
optional = true

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

