[package]
name = "dsf-core"
version = "0.2.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
description = "DSF core object definitions"
repository = "https://github.com/dist-svc/dsf-core"
homepage = "https://github.com/dist-svc"
keywords = ["DSF", "distributed"]
license = "MPL-2.0"
edition = "2018"

[features]
std = [ "managed/std", "bytes/std", "base64/std", "byteorder/std", "sha2/std", "chrono/std", "strum", "strum_macros", "thiserror" ]
alloc = [ "base64/alloc", "chrono/alloc", "pretty-hex/alloc" ]
default = [ "std", "serde" ]


[dependencies]
bitflags = "1.2.1"
#derive_builder = "0.7.0"
log = "0.4.6"
#ls = "0.0.0"
#newtype_array = "0.1.6"
slice-ext = "0.1.0"
async-trait = "0.1.19"
strum_macros = { version = "0.20.1", optional = true }
no-std-net = { version = "0.3.0", optional = true }
rand_core = { version = "0.5.1", default_features = false }
thiserror = { version = "1.0.11", default_features = false, optional = true }
defmt = { version = "0.2.1", optional = true }
derivative = "2.2.0"
pretty-hex = { version = "0.2.1", default_features = false }

[dependencies.managed]
version = "0.7.1"
default_features = false

[dependencies.sodiumoxide]
version = "0.2.5"
#git = "https://github.com/sodiumoxide/sodiumoxide.git"
#branch = "cc_build_libsodium"
default_features = false

[dependencies.bytes]
version = "1.0.1"
default_features = false

[dependencies.base64]
version = "0.12.1"
default_features = false

[dependencies.byteorder]
version = "1.3.2"
default_features = false

[dependencies.sha2]
version = "0.8.1"
default_features = false

[dependencies.chrono]
version = "0.4.11"
default_features = false

[dependencies.strum]
version = "0.20.0"
optional = true

[dependencies.diesel]
version = "1.4.3"
optional = true

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[patch.crates-io]
sodiumoxide = { git = "https://github.com/sodiumoxide/sodiumoxide.git" }

[dev-dependencies]
simplelog = "0.10.2"
